#!/usr/bin/env python3
"""Turn bench_eq's CSV into the evaluation table.

    dune exec bench_eq -- --reps 5 --csv bench.csv
    ./bench_table.py bench.csv --tex ~/caracara-paper/sections/evaluation/table.tex

The point of generating rather than transcribing is that the numbers in the
paper and the numbers the artifact produces cannot drift apart, and that
re-running on different hardware is a one-liner.

Two columns are worth explaining because they are the reason this exists.
`build` is everything between the checker calling solve() and Z3 being asked
anything: rewriting the query into the core fragment, walking it for region
declarations, and lowering it into Z3 AST nodes.  `solve` is Z3's own search.
They are different kinds of cost -- the first is ours and roughly linear in the
term's DAG, the second is Z3's and is not linear in anything -- and reporting
only their sum says which is which for neither.
"""

import argparse
import collections
import csv
import sys

# Families in the order the evaluation section discusses them.
ORDER = ["TSS", "P4", "eBPF", "ParserHawk"]


def load(path):
    with open(path) as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        for k in ("median_ms", "min_ms", "max_ms", "query_ms", "z3_ms"):
            if k in r and r[k]:
                r[k] = float(r[k])
        for k in ("smt_dag", "smt_tree", "smt_depth", "queries"):
            if k in r and r[k]:
                r[k] = int(r[k])
        r["dag"] = r["smt_dag"]
        r["depth"] = r["smt_depth"]
    return rows


def fam_key(name):
    return ORDER.index(name) if name in ORDER else len(ORDER)


def fmt_ms(x):
    """Milliseconds, always -- no switch to seconds past a threshold.  One unit
    down a column is what lets a reader compare two rows by eye; mixing them
    means every comparison needs a conversion first, and the one row that reads
    "1.4 s" beside forty that read in milliseconds is the row most likely to be
    misread by a factor of a thousand.

    Precision still varies: a tenth of a millisecond on a 1400 ms query is
    noise being quoted as signal, so only sub-10 ms numbers get a decimal."""
    if x >= 10:
        return "{:,.0f}".format(x)
    return "%.1f" % x


# The registry keys are terse; the table should read as prose.
PRETTY = {
    "TSS": "Packet classification",
}


def pretty(fam):
    return PRETTY.get(fam, fam)


def esc(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def is_witness(r):
    """A row that reports non-equivalence for a reason we are NOT happy about:
    an open bug, recorded so it is visible and flips when fixed.  Counting it
    among the controls would overstate how many cases actually probe the
    checker's ability to tell programs apart."""
    return "KNOWN FAILING" in r.get("what", "")


def summary(rows):
    """One line per family: how many cases, how big, and where the time goes."""
    out = []
    by = collections.defaultdict(list)
    for r in rows:
        by[r["family"]].append(r)
    for fam in sorted(by, key=fam_key):
        rs = by[fam]
        eq = sum(1 for r in rs if r["expected"] == "Equivalent")
        wit = sum(1 for r in rs if is_witness(r))
        dags = sorted(r["dag"] for r in rs)
        q = sorted(r["query_ms"] for r in rs)
        s = sorted(r["z3_ms"] for r in rs)
        out.append({
            "family": fam,
            "n": len(rs),
            "eq": eq,
            "ne": len(rs) - eq - wit,
            "wit": wit,
            "dag_med": dags[len(dags) // 2],
            "dag_max": dags[-1],
            "q_med": q[len(q) // 2],
            "q_max": q[-1],
            "s_med": s[len(s) // 2],
            "s_max": s[-1],
        })
    return out


def tex_summary(rows):
    # The known-failing pair lives in exactly one family's table now, so point
    # at that one rather than at a single combined table that no longer exists.
    wf = [r["family"] for r in rows if is_witness(r)]
    witness_ref = (r" Table~\ref{%s}." % fam_label(wf[0]) if wf
                   else r" the per-case tables.")
    L = [
        r"% Generated by bench_table.py from bench_eq's CSV; do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        r"& & \multicolumn{2}{c}{cases} & SMT & \multicolumn{2}{c}{median (ms)} \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){6-7}",
        r"family & $n$ & $\equiv$ & $\not\equiv$ & nodes & build & solve \\",
        r"\midrule",
    ]
    for s in summary(rows):
        L.append(
            "%s & %d & %d & %d & %s & %s & %s \\\\"
            % (esc(pretty(s["family"])), s["n"], s["eq"], s["ne"],
               "{:,}".format(s["dag_med"]),
               fmt_ms(s["q_med"]), fmt_ms(s["s_med"])))
    L += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Equivalence-checking benchmarks by family. $\equiv$ and"
        r" $\not\equiv$ count the cases whose expected verdict is equivalence"
        r" and non-equivalence; where they do not sum to $n$ the remainder is a"
        r" pair that \emph{should} be equivalent and is not, listed in"
        + witness_ref +
        r" \emph{SMT nodes} is the median count of distinct"
        r" subterms of the formula handed to Z3, sharing included. \emph{build} is the time"
        r" from the checker calling the solver to Z3 being asked anything"
        r" (rewriting into the core fragment, and lowering to Z3 AST);"
        r" \emph{solve} is Z3's search.}",
        r"\label{tab:bench}",
        r"\end{table}",
    ]
    return "\n".join(L)


def fam_label(fam):
    """A LaTeX label fragment for a family key.  The keys are already safe
    (letters, digits, one hyphen), so this only has to be stable -- the prose
    cites these, so do not derive it from the PRETTY name, which is prose and
    may be reworded."""
    return "tab:bench-" + fam.lower().replace(" ", "-")


def tex_cases_one(fam, sel):
    """One family's per-case table.

    Column-width `table`, not `table*`: with the family fixed there are five
    narrow columns left, which fit a column comfortably.  That also buys back
    what the old combined table could not have -- a `table` floats to the
    bottom of a page and to the page it is declared on, where a `table*` in a
    two-column layout can only reach the top of a later one.

    The family column is dropped rather than repeated down every row: it is
    constant here, and it is in the caption.
    """
    def cells(r):
        return [esc(r["case"]), "{:,}".format(r["dag"]),
                fmt_ms(r["query_ms"]), fmt_ms(r["z3_ms"]),
                (r"$\equiv$" if r["expected"] == "Equivalent"
                 else (r"$\not\equiv$\textsuperscript{\dag}" if is_witness(r)
                       else r"$\not\equiv$"))]

    body = [" & ".join(cells(r)) + r" \\" for r in sel]

    # The dagger legend belongs only to the table that actually carries one.
    dagger = (
        r" \textsuperscript{\dag}~marks a pair that \emph{should} be"
        r" equivalent and is not: a known imprecision in how a header narrower"
        r" than its container is seeded, which admits input values no packet"
        r" can produce. It is listed rather than omitted, and is not counted"
        r" among the controls."
        if any(is_witness(r) for r in sel) else "")

    return "\n".join([
        r"\begin{table}[tb]",
        r"\centering\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}lrrrc@{}}",
        r"\toprule",
        r"case & SMT & build & solve & $=$ \\",
        r"\midrule",
    ] + body + [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{%s: per-case detail. Columns as in"
        r" Table~\ref{tab:bench} --- \emph{SMT} is distinct subterms of the"
        r" formula given to Z3, \emph{build} and \emph{solve} are"
        r" milliseconds, and $=$ is the expected verdict.%s}"
        % (esc(pretty(fam)), dagger),
        r"\label{%s}" % fam_label(fam),
        r"\end{table}",
    ])


def tex_cases(rows, families):
    """Per-case detail, ONE FLOAT PER FAMILY.

    This used to be a single page-width `table*` with the rows dealt into two
    side-by-side blocks, which is what a fifty-row, seven-column table needs if
    it has to be one float.  Splitting by family removes that constraint: each
    table is short enough to place on its own, the reader is never asked to
    track which block a family continues in, and a family can be discussed
    beside its own numbers instead of beside a reference to a shared table.

    The cost is six floats rather than one, so LaTeX has more to place; if they
    bunch at the end, move the individual \\input lines next to the prose that
    cites them rather than fighting the placement specifiers.
    """
    sel = [r for r in sorted(rows, key=lambda r: (fam_key(r["family"]), r["case"]))
           if not families or r["family"] in families]

    by = collections.OrderedDict()
    for r in sel:
        by.setdefault(r["family"], []).append(r)

    out = [r"% Generated by bench_table.py from bench_eq's CSV;"
           r" do not edit by hand.",
           r"% One table per family; \label is tab:bench-<family>, lowercased."]
    for fam, frows in by.items():
        out.append("")
        out.append(tex_cases_one(fam, frows))
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--tex", help="write the summary table here")
    ap.add_argument("--cases-tex", help="write the per-case table here")
    ap.add_argument("--families", default="",
                    help="comma-separated, for the per-case table")
    args = ap.parse_args()

    rows = load(args.csv)
    bad = [r for r in rows if r.get("ok") == "0"]
    if bad:
        print("REFUSING: %d case(s) reported the wrong verdict; a timing for a"
              " query that answered the wrong question is not a timing worth"
              " quoting:" % len(bad), file=sys.stderr)
        for r in bad:
            print("  %s/%s: got %s want %s"
                  % (r["family"], r["case"], r["verdict"], r["expected"]),
                  file=sys.stderr)
        return 1

    fams = [f for f in args.families.split(",") if f]
    summ = tex_summary(rows)
    cases = tex_cases(rows, fams)
    if args.tex:
        open(args.tex, "w").write(summ + "\n")
        print("wrote %s" % args.tex)
    if args.cases_tex:
        open(args.cases_tex, "w").write(cases + "\n")
        print("wrote %s" % args.cases_tex)
    if not args.tex and not args.cases_tex:
        print(summ)

    # A couple of facts worth stating in prose rather than leaving to the
    # reader to compute off the table.
    tq = sum(r["query_ms"] for r in rows)
    ts = sum(r["z3_ms"] for r in rows)
    print("\n%d cases, %d equivalent / %d not."
          % (len(rows), sum(1 for r in rows if r["expected"] == "Equivalent"),
             sum(1 for r in rows if r["expected"] != "Equivalent")),
          file=sys.stderr)
    print("total build %.0f ms, total solve %.0f ms (build is %.0f%% of the"
          " work)" % (tq, ts, 100.0 * tq / (tq + ts) if tq + ts else 0),
          file=sys.stderr)
    slowest = max(rows, key=lambda r: r["z3_ms"])
    print("slowest solve: %s/%s at %.0f ms (%s SMT nodes)"
          % (slowest["family"], slowest["case"], slowest["z3_ms"],
             "{:,}".format(slowest["dag"])), file=sys.stderr)
    biggest = max(rows, key=lambda r: r["dag"])
    print("largest query: %s/%s at %s SMT nodes (build %.0f ms, solve %.0f ms)"
          % (biggest["family"], biggest["case"], "{:,}".format(biggest["dag"]),
             biggest["query_ms"], biggest["z3_ms"]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
