(* This file was generated by the P4->ROCQ compiler *)
From MyProject Require Import SmtExpr.
From MyProject Require Import SmtQuery.
From MyProject Require Import CrTransformer.
Require Import Strings.String.
Open Scope string_scope.
Require Import ZArith.
Require Import List.
Import ListNotations.

(* 1. Define Identifiers for Header Fields from P4 header: H *)
Definition h_a : Header := HeaderCtr 1%positive.
Definition h_b : Header := HeaderCtr 2%positive.

(* 2. Define the Action (Header Operation): MyAction1 *)
Definition MyAction1_op : HdrOp :=
  StatelessOp AddOp (ConstantArg (repr 1%Z)) (ConstantArg (repr 0%Z)) h_b.

(* 3. Define the Match-Action Rule for table: the_table_0 *)
Definition the_table_0_seq_rule : SeqRule :=
  SeqCtr
    [] (* Empty MatchPattern -> always matches *)
    [MyAction1_op].

Definition the_table_0_rule : MatchActionRule :=
  Seq the_table_0_seq_rule.
