#!/usr/bin/env perl
use strict;
use warnings;

-d 'extracted_code' or die "Run from the project root\n";
my $dune      = 'extracted_code/dune';
my $gitignore = '.gitignore';

# The hand-written extracted_code/*.ml files are exactly the ones the .gitignore
# un-ignores (everything else under extracted_code is generated by extraction).
# Keeping that list only in .gitignore means adding a new hand-written file is a
# one-line change there, and this script picks it up automatically.
open my $gi, '<', $gitignore or die "Cannot read $gitignore: $!";
my @handwritten;
while (<$gi>) {
    push @handwritten, $1 if m{^!/extracted_code/(\w+)\.ml\s*$};
}
close $gi;

# Hand-written files that live in their own dune stanzas rather than
# extracted_code_lib:
#   - standalone executables (each has its own (executable ...) stanza)
#   - ppx_expect test modules (the semantics_tests library), matched by Test* name
my %executable = map { $_ => 1 } qw(EqCheck DumpSexp);
my @tests  = sort grep {  /^Test/ && !$executable{$_} } @handwritten;
my @manual = sort grep { !/^Test/ && !$executable{$_} } @handwritten;

# extracted_code_lib modules: every extracted module (has a .mli) plus the
# hand-written library helpers, deduped and sorted.
my %seen;
my @modules = sort grep { !$seen{$_}++ }
    ( (map { /([^\/]+)\.mli$/; $1 } glob('extracted_code/*.mli')),
      @manual );

# Format the lib module list into wrapped lines (2-space indent, <=80 wide).
my ($indent, $width) = ('  ', 80);
my @lines;
my $line = $indent;
for my $m (@modules) {
    if    ($line eq $indent)                         { $line .= $m }
    elsif (length($line) + 1 + length($m) <= $width) { $line .= " $m" }
    else  { push @lines, $line; $line = "$indent$m" }
}
push @lines, $line if $line ne $indent;
my $formatted  = join "\n", @lines;
my $tests_line = join ' ', @tests;

# Read, patch, write.
open my $fh, '<', $dune or die "Cannot read $dune: $!";
my $text = do { local $/; <$fh> };
close $fh;

# Anchor to each stanza, then replace its (modules ...) block.  Module names
# contain no parens, so [^)]+ safely matches the whole block.
$text =~ s{
    (\(name \s+ extracted_code_lib\) .*?)  # anchor
    \ \(modules [^)]+ \)                   # existing modules block
}{$1 (modules\n$formatted)}xs
    or die "Could not find (modules ...) in extracted_code_lib stanza\n";

$text =~ s{
    (\(name \s+ semantics_tests\) .*?)     # anchor
    \ \(modules [^)]+ \)                   # existing modules block
}{$1 (modules $tests_line)}xs
    or die "Could not find (modules ...) in semantics_tests stanza\n";

open $fh, '>', $dune or die "Cannot write $dune: $!";
print $fh $text;
close $fh;

printf "Updated %s: %d lib modules, %d test modules.\n",
    $dune, scalar @modules, scalar @tests;
