(executable
 (public_name eq_check)
 (name EqCheck)
 (modules EqCheck)
 (libraries extracted_code_lib))

(executable
  (public_name mem_eq)
  (name MemEq)
  (modules MemEq)
  (libraries extracted_code_lib))

(executable
  (public_name dump_sexp)
  (name DumpSexp)
  (modules DumpSexp)
  (libraries extracted_code_lib))

(library
 (name semantics_tests)
 (modules TestEquality TestModuleSemantics TestProgramSemantics)
 (inline_tests
  (deps (source_tree ../test)))
 (preprocess (pps ppx_expect))
 (libraries extracted_code_lib))

(library
 (name extracted_code_lib)
 (wrapped false)
 (modules
  Ascii BinInt BinNums BinPos Coqlib CrConcreteSemanticsTransformer CrDsl
  CrDslProperties CrGeneralProgramState CrIdentifiers CrMem CrMemEx
  CrModConcreteSemantics CrModSymbolicSemantics CrModule CrParser CrProgramState
  CrSymbolicSemanticsTransformer CrTransformer CrTypeIF CrVal CrVarLike
  Datatypes EquivDec Integers List ListDef ListUtils Maps MemSolver Mergesort
  MyInts Nat NatDef Orders PeanoNat PktClass PosDef PosGraphLemmas Rocqlib Shim
  SmtExpr SmtModuleQuery SmtQuery SmtTypes Specif String TestModulePrograms
  TestPrograms Z3Solver ZArith_dec Zpower)
 (preprocess (staged_pps ppx_import ppx_sexp_conv))
 (libraries z3 sexplib)
 (flags (:standard -w -33)))
