(* This file was generated by the P4->ROCQ compiler *)
From MyProject Require Import SmtExpr.
From MyProject Require Import SmtQuery.
From MyProject Require Import CrTransformer.
From MyProject Require Import CrSymbolicSemantics.
From MyProject Require Import CrConcreteSemantics.
From MyProject Require Import ConcreteToSymbolicLemmas.
From MyProject Require Export CrIdentifiers.
From MyProject Require Export CrTransformer.
Require Import Strings.String.
Open Scope string_scope.
Require Import ZArith.
Require Import List.
Import ListNotations.

(* Header definition: H *)
Definition header_H : Header := HeaderCtr 1%positive.

(* Action: MyAction1 *)
Definition MyAction1_op : HdrOp := 
  StatelessOp AddOp (ConstantArg (repr 1%Z))  (ConstantArg (repr 0%Z)) header_H.

(* Table: the_table_0 *)
Definition the_table_0_seq_rule : SeqRule := 
  SeqCtr [(header_H, repr 0%Z)] [MyAction1_op]. 

Definition the_table_0_rule : MatchActionRule := 
  Seq the_table_0_seq_rule.

