name: Validate Build

on:
  pull_request:
    branches: [ master ]

jobs:
  automated-testing:
    runs-on: ubuntu-latest
    container:
      image: srhee/caracara:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build Project
        run: |
          eval $(opam env)
          coq_makefile -f _CoqProject *.v -o Makefile
          make -j
          dune build --profile release

      - name: Run OCaml Tests
        run: |
          eval $(opam env)
          dune exec run_tests
