name: Validate Build

on:
  pull_request:
    branches: [ master ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true

      - name: Cache switch
        uses: actions/cache@v4
        with:
          path: /home/runner/work/rocq_musings/rocq_musings/_opam
          # May want to figure out a better set of files to hash
          key: ${{ runner.os }}-switch-${{ hashFiles('/home/runner/work/rocq_musings/rocq_musings/dune-project', '/home/runner/work/rocq_musings/rocq_musings/extracted_code/dune') }}
          restore-keys: |
            ${{ runner.os }}-switch-

      - name: Install Switch
        run: |
          opam install -y coq.8.20.1 z3 ppx_import sexplib ppx_sexp_conv

  validate-build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Build Project
        run: |
          eval $(opam env)
          coq_makefile -f _CoqProject *.v -o Makefile
          make -j
          dune build --profile release

      - name: Run OCaml Tests
        run: |
          eval $(opam env)
          dune exec run_tests
